version: 1
disable_existing_loggers: false
formatters:
  default:
    (): uvicorn.logging.DefaultFormatter
    fmt: '[%(asctime)s|%(name)s|%(levelname)s] %(message)s'
    use_colors: false
  
  default-color:
    (): uvicorn.logging.DefaultFormatter
    fmt: '[%(asctime)s|%(name)s] %(levelprefix)s %(message)s'
    use_colors: true

  access:
    (): uvicorn.logging.AccessFormatter
    fmt: >-
      [%(asctime)s|%(name)s|%(levelname)s] %(client_addr)s -
      '%(request_line)s' %(status_code)s
    use_colors: false

  
  access-color:
    (): uvicorn.logging.AccessFormatter
    fmt: >-
      [%(asctime)s|%(name)s] %(levelprefix)s %(client_addr)s -
      '%(request_line)s' %(status_code)s
    use_colors: true
  
handlers:
  default:
    formatter: default-color
    class: logging.StreamHandler
    stream: 'ext://sys.stderr'
  default_file:
    formatter: default
    class: logging.handlers.TimedRotatingFileHandler
    filename: backend/logs/app.default.log
    when: midnight
    encoding: utf-8
    backupCount: 10
  access:
    formatter: access-color
    class: logging.StreamHandler
    stream: 'ext://sys.stdout'
  access_file:
    formatter: access
    class: logging.handlers.TimedRotatingFileHandler
    filename: backend/logs/app.access.log
    when: midnight
    encoding: utf-8
    backupCount: 10
loggers:
  uvicorn:
    handlers:
      - default
      - default_file
    level: INFO
    propagate: false
  uvicorn.error:
    level: INFO
  uvicorn.access:
    handlers:
      - access
      - access_file
    level: INFO
    propagate: false
